services:
  - type: web
    name: Fabio_de_Paula
    env: node
    plan: free
    repo: https://github.com/fabiobatata/meu-web-postgres
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: meu-postgres
          property: connectionString

databases:
  - name: meu-postgres
    plan: free
    region: oregon